CREATE TABLE STG1_PRODUCTO (
	CODIGO_PRODUCTO INT,
	PRODUCTO varchar(100)
);

CREATE TABLE STG2_PRODUCTO (
	CODIGO_PRODUCTO INT,
	PRODUCTO varchar(100)
);

CREATE TABLE STG3_PRODUCTO (
	CODIGO_PRODUCTO INT,
	PRODUCTO varchar(100)
);

CREATE TABLE PRODUCTO (
	ID_PRODUCTO INT,
	PRODUCTO varchar(100)
);